spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blindBox?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080

#aliyun:
#  oss:
#    endpoint:
#    accessKeyId:
#    accessKeySecret:
#    bucketName:
