spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blindBox?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5t8EjSmpBHbEQWsZcf7V
    accessKeySecret: DS3o0ZmHmOGuWTGHUvpSt8KeZp7bK8
    bucketName: my-bucket070011
